### ISSUE TITLE
please add credit

### ISSUE THREAD

**Issue by badgeek** [LavaLite/cms#228]
looks like you are using some part of my Laravel Db Designer, would be awesome if you also put my credits on it 

thanks

**Comment by Renfos** [comment]
Hi Badgeek,
Thanks for your wonderful laravel db designer component. It was very useful in developinf the package generator. Will add your credits on next update of our website.

**Comment by badgeek** [comment]
awesome!, glad to find this useful ! i have no time to continue the development right now...

**Comment by helpmyworld** [comment]
May i ask something i can only hope that this is the right platform to get understanding, if not may you direct me to the relevant source. 

I just started learning laravel and php, i stumbled into this project. As we speak i am still reading and learning what i can. 

My learning need is what is this ''LavaLite'' and what does it do? I was searching for CMS because  want to build a cms website. So far i am reading the documentation but i am not clear on what i am doing. Perhaps a crush course and background will do. 

Thank you
